name: Build and Publish Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install rpm-build
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Build Electron App
        run: npm run make

      - name: Set up Git identity
        run: |
          git config --global user.name "dradvm"
          git config --global user.email "duynnvn2511@gmail.com"

      - name: Deploy App to Github Pages
        run: npm run deploy

      - name: Publish to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish
